### ISSUE TITLE
Add default, recommended config

### ISSUE THREAD

**Issue by keplersj** [bradzacher/eslint-plugin-typescript#109]
Similar to other ESLint plugins like this ([flowtype](https://github.com/gajus/eslint-plugin-flowtype#shareable-configurations), [react](https://github.com/yannickcr/eslint-plugin-react#shareable-configurations), etc.) it would be really helpful if this plugin exported shareable configs. Perhaps configs aiming for parity with [TSLint's built in configs](https://palantir.github.io/tslint/usage/configuration/#configuration-presets) would be the most appropriate.

Edit: I'd be happy to submit a Pull Request implementing this if it interests you.

**Comment by mightyiam** [comment]
BTW, https://www.npmjs.com/package/eslint-config-standard-with-typescript

**Comment by deepsweet** [comment]
+1 here, would love to see `plugin:typescript/recommended` or something similar in my configuration:

```json
"extends": [
  "standard",
  "plugin:node/recommended",
  "plugin:promise/recommended",
  "plugin:import/recommended",
  "plugin:flowtype/recommended",
  "prettier",
  "prettier/standard",
  "prettier/flowtype"
],
```

**Comment by bradzacher** [comment]
Closing in favour of #144
