### ISSUE TITLE
[Bug] Parsing error

### ISSUE THREAD

**Issue by KindWizzard** [bradzacher/eslint-plugin-typescript#128]
Hello guys! 

For some reason, this code leads to different errors in eslint:

```
function esTsFail(event):number {
	return (<MouseEvent>event).clientX;
}
```

**Comment by macklinu** [comment]
Could you please include the errors you are seeing and your ESLint configuration?

**Comment by macklinu** [comment]
Here's a reproducible [AST explorer](http://astexplorer.net/#/gist/58537ff3964ce6aff61922af7e721663/023624ac362be9fd4222383326aedaf5d4b9fac7).

This may or may not be related to #130 - wanted to link the issues together in case they were.

**Comment by bradzacher** [comment]
Looking at the bug in the AST explorer - it only occurs if you have `jsx: true` on in the parser options. Turning off jsx mode, it parses fine.

```JSON
{
	"parserOptions": {
		"ecmaFeatures": {
			"jsx": false
		}
	}
}
```


I'm going to go ahead and close this issue.

If @KindWizzard has a follow up, we can consider reopening.

**Comment by j-f1** [comment]
As a workaround, you can use this syntax instead:

```ts
function esTsFail(event):number {
	return (event as MouseEvent).clientX;
}
```
