### ISSUE TITLE
add a recommended preset

### ISSUE THREAD

**Issue by Aladdin-ADD** [bradzacher/eslint-plugin-typescript#144]

**Comment by benjie** [comment]
Can anyone share the typescript rules they're using? Do you just copy/paste from the README and set them all to 'error'?

**Comment by jorgegonzalez** [comment]
We're using [these](https://github.com/jorgegonzalez/zoe/blob/master/configs/typescript.json) in [Zoe](https://github.com/jorgegonzalez/zoe).

**Comment by ChristianStornowski** [comment]
Im using this tslint recommendation aligned configuration:

    ```
    "typescript/no-type-alias": "error",
    "typescript/explicit-member-accessibility": "error",
    "typescript/member-ordering": "error",
    "typescript/no-angle-bracket-type-assertion": "error",
    "typescript/no-empty-interface": "error",
    "typescript/prefer-namespace-keyword": "error",
    "typescript/no-namespace": "error",
    "typescript/no-parameter-properties": "error",
    "typescript/no-triple-slash-reference": "error",
    "typescript/no-var-requires": "error",
```

**Comment by ChristianStornowski** [comment]
I did some homework:

https://www.npmjs.com/package/eslint-config-typescript-recommended

Maybe it could be integrated into this plugin. :-)

**Comment by j-f1** [comment]
@ChristianStornowski a quick note: `valid-jsdoc` is different from `jsdoc-format` because it checks for content of the JSDoc instead of just syntax.

**Comment by ChristianStornowski** [comment]
Thanks for this hint. :-)

If i'm reading this correct: https://eslint.org/docs/rules/valid-jsdoc#options

i only have to set `requireReturn` to `false` and only syntax check is enabled.

**Comment by j-f1** [comment]
@ChristianStornowski Unfortunately, [it will still error if a value is explicitly returned](https://eslint.org/demo/#eyJ0ZXh0IjoiLyogZXNsaW50IHZhbGlkLWpzZG9jOiBbZXJyb3IsIHsgcmVxdWlyZVJldHVybjogdHJ1ZSB9XSAqL1xuXG4vKipcbiAqIGdldHMgdGhlIGFuc3dlclxuICovXG5mdW5jdGlvbiB0aGVBbnN3ZXIoKSB7XG4gIHJldHVybiA0MlxufSIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6NSwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6e30sImVudiI6e319fQ==).

**Comment by weirdpattern** [comment]
I'm the owner of [eslint-config-typescript](https://www.npmjs.com/package/eslint-config-typescript) and my intention was (and still is) to complement this project with that one... I'm willing to work with anyone that is interested in making that happen :smile:

**Comment by ChristianStornowski** [comment]
They are different projects in the npm world:

https://www.npmjs.com/package/eslint-config-standard-with-typescript
https://www.npmjs.com/package/eslint-config-typescript
https://www.npmjs.com/package/eslint-config-typescript-recommended

we should combine them together.

The question is who should be the owner. Should be eslint-plugin-typescript the owner for this configs?

**Comment by mightyiam** [comment]
Re: combining them together

I am the person behind https://www.npmjs.com/package/eslint-config-standard-with-typescript.

I don't see a good reason for combining them together.

Further, I feel that recommendations should be outside the scope of this project.

Let the community provide shareable configs, is how I see it. I would close this issue.

**Comment by benjie** [comment]
Definitely add them to the README though 👍

**Comment by bradzacher** [comment]
It's common practice for plugin authors to provide at the very least a "recommended" config set, if not more than that [[1]](https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/src/index.js#L41-L233) [[2]](https://github.com/yannickcr/eslint-plugin-react/blob/master/index.js#L116-L149) [[3]](https://github.com/benmosher/eslint-plugin-import/tree/master/config) [[4]](https://github.com/jest-community/eslint-plugin-jest/blob/master/index.js#L35-L61)

The idea is to ease adoption of the plugin: i.e. "I like the idea of linting [react/typescript/jest/etc], but I don't want to read the docs and configure each rule myself, I'll start with the recommended and then tweak based on what I love/hate".

We'll definitely be looking to add at least a recommended config; we'll review the community (i.e. all of your) configs and figure out what is the best recommendation.

Aim will be to have this in for the 1.0.0 release.

**Comment by bradzacher** [comment]
(copying comment from https://github.com/bradzacher/eslint-plugin-typescript/pull/204#issuecomment-446074939 for visibility)

-----

I went through 4 configs that I know with config for our plugin, and came up with the following recommendations by merging them together.

Please provide feedback.


## The configs for reference, with keys sorted:
<details><summary>eslint-config-typescript-recommended</summary>
<p>

https://github.com/diva-e/eslint-config-typescript-recommended/blob/master/index.js#L124-L140

```JSON
{
    "typescript/adjacent-overload-signatures": "error",
    "typescript/class-name-casing": "error",
    "typescript/explicit-member-accessibility": "error",
    "typescript/interface-name-prefix": ["error", "always"],
    "typescript/member-ordering": "error",
    "typescript/no-angle-bracket-type-assertion": "error",
    "typescript/no-empty-interface": "error",
    "typescript/no-explicit-any": "off",
    "typescript/no-namespace": "error",
    "typescript/no-parameter-properties": "off",
    "typescript/no-triple-slash-reference": "error",
    "typescript/no-type-alias": "error",
    "typescript/no-var-requires": "error",
    "typescript/prefer-namespace-keyword": "error"
}
```

</p>
</details>

<details><summary>eslint-config-typescript</summary>
<p>

https://github.com/weirdpattern/eslint-config-typescript/blob/master/src/typescript.js#L21-L68

```JSON
{
    "typescript/adjacent-overload-signatures": "error",
    "typescript/class-name-casing": "error",
    "typescript/explicit-function-return-type": [
        "error",
        {
            "allowExpressions": true
        }
    ],
    "typescript/explicit-member-accessibility": "error",
    "typescript/interface-name-prefix": "error",
    "typescript/member-delimiter-style": "error",
    "typescript/member-ordering": [
        "error",
        {
            "default": [
                "static-field",
                "private-field",
                "protected-field",
                "public-field",
                "constructor",
                "public-method",
                "protected-method",
                "private-method"
            ]
        }
    ],
    "typescript/no-angle-bracket-type-assertion": "error",
    "typescript/no-array-constructor": "error",
    "typescript/no-inferrable-types": [
        "error",
        {
            "ignoreProperties": true,
            "ignoreParameters": true
        }
    ],
    "typescript/no-namespace": [
        "error",
        {
            "allowDeclarations": true
        }
    ],
    "typescript/no-non-null-assertion": "error",
    "typescript/no-parameter-properties": "error",
    "typescript/no-triple-slash-reference": "error",
    "typescript/no-use-before-define": "error",
    "typescript/no-var-requires": "error",
    "typescript/prefer-namespace-keyword": "error",
    "typescript/type-annotation-spacing": "error"
}
```

</p>
</details>

<details><summary>eslint-config-standard-with-typescript</summary>
<p>

https://github.com/mightyiam/eslint-config-standard-with-typescript/blob/master/src/index.ts#L19-L32

```JSON
{
    "typescript/adjacent-overload-signatures": "error",
    "typescript/explicit-function-return-type": "error",
    "typescript/explicit-member-accessibility": "error",
    "typescript/member-delimiter-style": [
        "error",
        {
            "delimiter": "none"
        }
    ],
    "typescript/no-angle-bracket-type-assertion": "error",
    "typescript/no-array-constructor": "error",
    "typescript/no-empty-interface": "error",
    "typescript/no-namespace": "error",
    "typescript/no-non-null-assertion": "error",
    "typescript/no-triple-slash-reference": "error",
    "typescript/no-unused-vars": "error",
    "typescript/no-use-before-define": [
        "error",
        {
            "functions": false,
            "classes": false,
            "variables": false,
            "typedefs": false
        }
    ],
    "typescript/no-var-requires": "error",
    "typescript/type-annotation-spacing": "error"
}

```

</p>
</details>

<details><summary>eslint-config-assignar</summary>
<p>

This is the last company I worked at, and I did the eslint config :)
https://github.com/assignar/eslint-config-assignar/blob/develop/packages/eslint-config-assignar-base/src/plugins/typescript.ts

```JSON
{
    "typescript/adjacent-overload-signatures": "error",
    "typescript/class-name-casing": "error",
    "typescript/explicit-function-return-type": "off",
    "typescript/explicit-member-accessibility": "error",
    "typescript/interface-name-prefix": ["warn", "never"],
    "typescript/member-delimiter-style": [
        "error",
        {
            "delimiter": "none",
            "requireLast": true,
            "ignoreSingleLine": true
        }
    ],
    "typescript/member-naming": "off",
    "typescript/member-ordering": "off",
    "typescript/no-angle-bracket-type-assertion": "error",
    "typescript/no-array-constructor": "error",
    "typescript/no-empty-interface": "off",
    "typescript/no-explicit-any": "warn",
    "typescript/no-inferrable-types": "off",
    "typescript/no-namespace": [
        "error",
        {
            "allowDeclarations": false,
            "allowDefinitionFiles": true
        }
    ],
    "typescript/no-non-null-assertion": "warn",
    "typescript/no-parameter-properties": "error",
    "typescript/no-triple-slash-reference": "warn",
    "typescript/no-type-alias": "off",
    "typescript/no-unused-vars": "error",
    "typescript/no-use-before-define": "error",
    "typescript/no-var-requires": "off",
    "typescript/prefer-namespace-keyword": "off",
    "typescript/type-annotation-spacing": [
        "error",
        {
            "before": false,
            "after": true,
            "overrides": {
                "arrow": {
                    "before": true,
                    "after": true
                },
                "colon": {
                    "before": false,
                    "after": true
                }
            }
        }
    ]
}
```

</p>
</details>

## Recommended Config

```JSON
{
    "typescript/adjacent-overload-signatures": "error",
    "typescript/ban-types": [
        "error",
        {
            "types": {
                "Boolean": {
                    "message": "Use boolean instead",
                    "fixWith": "boolean"
                },
                "Number": {
                    "message": "Use number instead",
                    "fixWith": "number"
                },
                "Object": {
                    "message": "Use Record<string, any> instead",
                    "fixWith": "Record<string, any>"
                },
                "Symbol": {
                    "message": "Use symbol instead",
                    "fixWith": "symbol"
                }
            }
        }
    ],
    "typescript/camelcase": [
        "error",
        {
            "allow": ["^UNSAFE_"],
            "ignoreDestructuring": false,
            "properties": "never"
        }
    ],
    "typescript/class-name-casing": "error",
    "typescript/explicit-function-return-type": [
        "error",
        {
            "allowExpressions": true
        }
    ],
    "typescript/explicit-member-accessibility": "error",
    "typescript/generic-type-naming": ["error", "'^T[A-Z][a-zA-Z]+$'"],
    "typescript/interface-name-prefix": ["error", "never"],
    "typescript/member-delimiter-style": "error",
    "typescript/member-ordering": "error",
    "typescript/no-angle-bracket-type-assertion": "error",
    "typescript/no-array-constructor": "error",
    "typescript/no-empty-interface": "error",
    "typescript/no-explicit-any": "error",
    "typescript/no-inferrable-types": [
        "error",
        {
            "ignoreProperties": true,
            "ignoreParameters": true
        }
    ],
    "typescript/no-namespace": [
        "error",
        {
            "allowDeclarations": true
        }
    ],
    "typescript/no-non-null-assertion": "error",
    "typescript/no-parameter-properties": "error",
    "typescript/no-triple-slash-reference": "error",
    "typescript/no-type-alias": "off",
    "no-unused-vars": "off",
    "typescript/no-unused-vars": "off",
    "typescript/no-use-before-define": "error",
    "typescript/no-var-requires": "error",
    "typescript/prefer-namespace-keyword": "error",
    "typescript/type-annotation-spacing": "error"
}
```

**Comment by corbinu** [comment]
@bradzacher is typescript/no-unused-vars supposed to be off?

Just a few thoughts that are totally my personal opinion

- typescript/explicit-function-return-type - I would turn off but I still think it should be recommended
- typescript/no-explicit-any - I would turn off but I still think it should be recommended
- typescript/no-angle-bracket-type-assertion - This is only for those using JSX the other syntax is still used a lot in libs unrelated to React
- typescript/generic-type-naming - This regex rejects just a straight T which seems a little odd to me but would love to hear others thoughts

**Comment by j-f1** [comment]
@corbinu For the angle bracket type assertion, I think the `as` syntax is much easier to read.

**Comment by corbinu** [comment]
@j-f1 guess maybe it just looks natural to me as Java was the second language ;) and also because I started in TypeScript so early when this was the norm. 

Either way I do think that the recommended settings should favor conforming to how typescript programmers currently format their code rather than be prescriptive as that will most likely hurt adoption. A lot of large old TypeScript projects still use the bracket format. Plus if they want a more prescriptive format that is kinda what Prettier is for in my mind.

**Comment by armano2** [comment]
recomended configuration should be default one set in rule, that user is not forced to setup configuration to make it work, for example:

```js
"typescript/no-namespace": [ "error", {
  "allowDeclarations": true
}],
```
`allowDeclarations` should be set by default to true

**Comment by j-f1** [comment]
> Plus if they want a more prescriptive format that is kinda what Prettier is for in my mind.

Note that Prettier doesn’t prescribe a style here — its goal is to print the syntax as-is without changing it.

**Comment by corbinu** [comment]
@j-f1 guess we will have to disagree here I am basing this on prettier's "An opinionated code formatter" from their docs. I feel like that is not the goal of prettier even if it is not the current behavior of prettier

**Comment by bradzacher** [comment]
@corbinu 
> typescript/explicit-function-return-type - I would turn off but I still think it should be recommended

Probably best for us to turn it on as a warning then?
I'm not sure what to do with these "best practice" types of rules. Do we turn them on because they're best practices that aren't followed a lot, or do we turn them off because they're hard for people to get used to?

> typescript/no-explicit-any - I would turn off but I still think it should be recommended

Being an experienced TS dev; I personally prefer it on, but on as a warning. If only so that other devs on my team are less likely to use any 😄.
One of the biggest problems I've seen with new TS devs is that they often throw their hands up in the air and drop an `any` when typing gets a little hard (a side effect of devs trying to write TS as if it was JS).

I'm of the opinion that using `any` is a code-smell, and we should recommend you don't do it.

> typescript/no-angle-bracket-type-assertion - This is only for those using JSX the other syntax is still used a lot in libs unrelated to React

From what I've seen in the docs that the TS team releases, using `as` is the new standard. Using angle brackets causes confusion with JSX syntax and is ultimately ugly syntax.

I came from a java/c++/c# background, but I much prefer the as syntax anyways; much easier to follow. 
Definitely prefer it to flow's casting as well `const x = ('asdf': MyType)`

> typescript/generic-type-naming - This regex rejects just a straight T which seems a little odd to me but would love to hear others thoughts

I just copy pasted the regex. But in an ideal world you should *probably* name your generics with more than just `T`. We can defs change it to allow just the single `T` though, considering that's what most people do with a single generic.
(hey, maybe we should add this as a config option?)

I'm not sure if that should be there though... is that considered an anti-pattern in TS now? (similar to how `IInterface` is an antipattern now).


---

@armano2 Yeah we'll figure out what our defaults are with this recommended set, and we'll make the changes across the board to match.

**Comment by ChristianStornowski** [comment]
Maybe we should considering https://github.com/palantir/tslint/issues/1142. There are a lot of discussions and implementation https://github.com/palantir/tslint/commits/master to be more aligned with https://www.npmjs.com/package/tslint-microsoft-contrib.

**Comment by corbinu** [comment]
@bradzacher Thanks for the feedback makes sense as for the "best practice" types of rules I have seen a lot of eslint packages have both an "essential" config that doesn't include them and then a "recommended" that does.

**Comment by bradzacher** [comment]
See #261

**Comment by corbinu** [comment]
@bradzacher I have started using this however I am getting errors that the recommended config sets some rules as "warning" instead of "warn" for example "typescript/explicit-function-return-type"

**Comment by j-f1** [comment]
#263 @corbinu

**Comment by corbinu** [comment]
@j-f1 Thanks!
