### ISSUE TITLE
Looking for new maintainer(s)

### ISSUE THREAD

**Issue by nzakas** [bradzacher/eslint-plugin-typescript#165]
Hi everyone,

As you may or may not know, I started this plugin a while ago as an adjunct to TypeScript support in ESLint. Unfortunately, my health has not been good and I haven't really been able to maintain this project properly. @JamesHenry was handling this in my absence, but now he also is unable to continue maintaining this project.

While my health has improved, I just don't have enough energy to keep up with issues and pull requests on this project, and so I'm looking for someone (or a group of someone) who is willing to take on this project and continue updating and iterating on it.

If you're interested in seeing this project continue and are willing to continue working on it, please comment below. I'm happy to transfer the project to whomever is interested.

Thanks!

**Comment by rishichawda** [comment]
@nzakas Would be happy to take over the project. Although I'm new to typescript, I have a few people who are willing to work with on typescript.

**Comment by rishichawda** [comment]
@nzakas I would be happy to take over the project. Although I'm new to typescript, I have a few people who are willing to work with me on typescript. Also, because I love eslint. :)

**Comment by JamesHenry** [comment]
cc @macklinu @j-f1 @bradzacher as they are the top external contributors to date

**Comment by weirdpattern** [comment]
😭 @JamesHenry, I know I've been away for a while... but I keep taps with the repository 😃...
I would love to help, but I think it would be better if we have multiple maintainers as I can't guarantee I will always have time...

**Comment by corbinu** [comment]
I don't have to much time but would be happy to review PRs and such as I love this project.

**Comment by bradzacher** [comment]
I'd be glad to maintain/take ownership of this project.

I love typescript and I've really enjoyed the time I've spent working on linting projects.

I also need a reason to spend less time playing slay the spire on the shuttle :)

**Comment by j-f1** [comment]
I also don’t think I’d be able to take a major role, but I can definitely review PRs, helpmout with issues, and provide some support.

**Comment by nzakas** [comment]
Thanks everyone. I think the best path forward is to assign everything to @bradzacher and let him decide how to go from there.

Brad - I've sent you an invite to this repo. Once, you get it, I think you'll be able to transfer the repo to yourself. If not, let me know and I'll do it. Then let me know your npm username and I'll make you an owner of the package.

**Comment by bradzacher** [comment]
I don't have access to do the transfer, I think the owner is the only one who has access to do that on a non-org repo.

My npm is the same as my github: `bradzacher`

**Comment by nzakas** [comment]
Okay, transfer incoming.

**Comment by nzakas** [comment]
@bradzacher So it looks like because you already have a fork named `bradzacher/eslint-plugin-typescript` that I can't transfer this repo to you. To continue, you'd need to delete your fork. If you any branches of current work that haven't been merged into this repo yet, you should be able to push them into a remote branch on this repo now. Let me know when you've done all that and I'll do the transfer again.

I've added you as a maintainer of npm.

**Comment by bradzacher** [comment]
My fork is deleted!

**Comment by nzakas** [comment]
All right, the repo is on its way.

**Comment by JamesHenry** [comment]
Awesome! @bradzacher I am going to officially unwatch the repo now, but please feel free to @ me at any time

**Comment by bradzacher** [comment]
Thanks heaps to both @nzakas and @JamesHenry for everything you've done.

@corbinu @macklinu @j-f1 @weirdpattern
If you are up for it, I'm happy to add any/all of you as "Collaborators".

I'd appreciate any help you can provide in reviewing / merging PRs and triaging issues.

**Comment by macklinu** [comment]
@macklinu happy to be added as a collaborator!

**Comment by j-f1** [comment]
Glad to help!

**Comment by nzakas** [comment]
Thanks to everyone for taking this project over. It deserves a lot more love than I'm able to give right now.

As with @JamesHenry, I'm going to unsubscribe from this repo now, but feel free to at-mention me if you need clarification on something.

**Comment by milesj** [comment]
Awesome stuff, let me know if you need help. I'm open to reviewing PRs.

And feel better @nzakas, thanks for the great work!
