### ISSUE TITLE
[no-unused-vars] How to configure?

### ISSUE THREAD

**Issue by ficristo** [bradzacher/eslint-plugin-typescript#170]
I have this ESLint rule:
`"no-unused-vars": [1, {"vars": "all", "args": "none"}],`
if I add the `typescript/no-unused-vars` rule should I add all options to it too?
Or configuring it to something like `typescript/no-unused-vars : 1` will inherit all options?

Sorry to not use the templates, my question doesn't seem to match any of them.

**Comment by j-f1** [comment]
You should just be able to change `no-unused-vars` to `typescript/no-unused-vars`. You don’t want to keep the core rule enabled since it might crash, as you’ve seen.

**Comment by j-f1** [comment]
I’m closing this for now, but please feel free to comment still if you have any issues.

**Comment by ficristo** [comment]
According to the [docs](https://github.com/bradzacher/eslint-plugin-typescript/blob/67ad1cb71e90e18b9f0bf9bb80d394f3850c4cf8/docs/rules/no-unused-vars.md)
> This rule only has an effect when the no-unused-vars core rule is enabled.

So now I'm a bit more confused...

**Comment by ficristo** [comment]
Also consider my actual configuration is a bit more complex, with mixed js, ts and tsx rules.
See https://github.com/quadre-code/quadre/blob/1d180aa9325d084fc6780a7078506e51fde47b6d/.eslintrc.js

**Comment by j-f1** [comment]
I never noticed that before. Seems like we should try to implement the core rule here or find a workaround for the error.

**Comment by bradzacher** [comment]
@j-f1 Our rule builds upon the standard eslint rule.

Essentially the default rule marks variable/class/function/argument definitions as used by adding `eslintUsed: true` to the definition.

Our rule just adds additional handling for the extra definition and use cases that typescript adds; marking things as `eslintUsed` where applicable.

Which is why there's always so many issues against it, because we have to find all of the new cases.

**Comment by bradzacher** [comment]
we should probably add a check to the rule so that it ensures that you have the base rule enabled.

**Comment by ficristo** [comment]
If I understood correctly, it inherits all the options of the `base no-unused-var` rule?

**Comment by j-f1** [comment]
@ficristo Almost. It marks the type variables as used, and `no-unused-vars` reports all the issues.
