### ISSUE TITLE
Add explicit dependencies

### ISSUE THREAD

**Issue by bradzacher** [bradzacher/eslint-plugin-typescript#184]
We have a peer dependency on `eslint`, and a direct dependency on `typescript-eslint-parser`.

I've submitted https://github.com/eslint/eslint/issues/11127, maybe it'll be considered.

Regardless, we should at least be explicitly defining our required versions via peer dependencies.

(as per discussion on #183)

**Comment by weirdpattern** [comment]
I will assign this to myself...
