### ISSUE TITLE
Incorrect README or parse not published?

### ISSUE THREAD

**Issue by donaldpipowitch** [bradzacher/eslint-plugin-typescript#198]
**Repro**

`$ npm install eslint-plugin-typescript`

**Expected Result**

`node_modules/eslint-plugin-typescript/parser.js` exists.

**Actual Result**

`node_modules/eslint-plugin-typescript/parser.js` doesn't exist.

**Additional Info**

The README says:

> Add eslint-plugin-typescript/parser to the parser field.

And it is shown that way in the example below.

**Versions**

| package                    | version |
| -------------------------- | ------- |
| `eslint-plugin-typescript` | `0.14.0` |
| `typescript-eslint-parser` | `X.Y.Z` |
| `typescript`               | `X.Y.Z` |

**Comment by bradzacher** [comment]
Hi @donaldpipowitch,
The readme changes are part of the upcoming 1.0.0 release.
For the current release readme, please see the tag corresponding to the release (https://github.com/bradzacher/eslint-plugin-typescript/tree/0.14.0), or see the readme on npm

**Comment by donaldpipowitch** [comment]
Cool, thank you 😎
