### ISSUE TITLE
Support for typed TSLint rules

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [bradzacher/eslint-plugin-typescript#276]
TSLint has some rules that use [typed checked rules](https://palantir.github.io/tslint/usage/type-checking/) are able to tap into the full type intelligence from TypeScript, so they can leverage the full type system in their linting. 

<details><summary><em>(some higher value rules that aren't really possible without type information here...)</em></summary>
<p>

<ul>
    <li><a href="https://palantir.github.io/tslint/rules/no-unnecessary-type-assertion/">no-unnecessary-type-assertion/</a></li>
    <li><a href="https://palantir.github.io/tslint/rules/await-promise/">await-promise/</a></li>
    <li><a href="https://palantir.github.io/tslint/rules/no-floating-promises">no-floating-promises</a></li>
    <li><a href="https://palantir.github.io/tslint/rules/no-for-in-array">no-for-in-array</a></li>
    <li><a href="https://palantir.github.io/tslint/rules/no-unbound-method">no-unbound-method</a></li>
    <li><a href="https://palantir.github.io/tslint/rules/no-unsafe-any">no-unsafe-any</a></li>
    <li><a href="https://palantir.github.io/tslint/rules/restrict-plus-operands">restrict-plus-operands</a></li>
    <li><a href="https://palantir.github.io/tslint/rules/strict-boolean-expressions">strict-boolean-expressions</a></li>
    <li><a href="https://palantir.github.io/tslint/rules/strict-type-predicates">strict-type-predicates</a></li>
    <li><a href="https://palantir.github.io/tslint/rules/prefer-readonly/">prefer-readonly/</a></li>
    <li><a href="https://palantir.github.io/tslint/rules/unnecessary-bind">unnecessary-bind</a></li>
</ul>

</p>
</details>
<br />

Although versions of some typed rules are available in ESLint & its plugins, they fall apart when interacting with objects whose types can't be inferred statically using just the file: for example, if linting code that imports objects from another file/module.

The recent [TypeScript Jan-Jun 2019 Roadmap](https://github.com/Microsoft/TypeScript/issues/29288) reminded me of a [tweeted suggestion](https://twitter.com/slicknet/status/1069985853261271042) to file this here. Is this the right place? Would ESLint core need structural improvements to support full-program type checking?

**Comment by armano2** [comment]
@JoshuaKGoldberg we started working on rules like this :)
https://github.com/bradzacher/eslint-plugin-typescript/pull/250

**Comment by JoshuaKGoldberg** [comment]
Ooh! Looking through that PR:

> `context.parserServices.program.getTypeChecker();`

TIL that's available, great! Do you have docs on this? I can't find any in this repo.

**Comment by j-f1** [comment]
There’s a PR open in `typescript-eslint-parser` to add a way for rules to get type information: https://github.com/eslint/typescript-eslint-parser/pull/568. Once that’s merged, we’d appreciate help creating rules that use this type info!

**Comment by JoshuaKGoldberg** [comment]
I'll close this issue in favor of making two dedicated ones: docs and rule parity. Thanks! 😍

**Comment by j-f1** [comment]
We don’t have docs here as far as I know, but `getTypeChecker()` returns an instance of TS’s `TypeChecker` class provided directly by TS.

**Comment by j-f1** [comment]
I’m wondering if we should move all the TS+ESLint stuff to an @eslint-typescript org so changes can be released more quickly.
