### ISSUE TITLE
Support typescript indentation

### ISSUE THREAD

**Issue by dwasyluk** [bradzacher/eslint-plugin-typescript#96]
It doesnt seem like tslint indent is supported, which exposes things like interfaces to inconsistent spacing.

**Comment by weirdpattern** [comment]
Hi @dwasyluk, thanks for submitting this issue. Could you please provide an example?
Any kind of documentation will also be very helpful (maybe a link to TSLint?)

**Comment by armano2** [comment]
#219

**Comment by bradzacher** [comment]
closing this in favor of #201
